FROM rust:1.88.0-alpine AS builder

RUN apk add --no-cache \
    git \
    perl \
    make \
    musl-dev \
    openssl-dev \
    openssl-libs-static \
    pkgconfig

WORKDIR /usr/src/ord

COPY . .

RUN cargo build --bin ord --release

FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=builder \
    /usr/src/ord/target/release/ord \
    /usr/local/bin/ord

ENV RUST_BACKTRACE=1
ENV RUST_LOG=info
